### ISSUE TITLE
Is it possible to change Icon everyday with Adaptive Icon?

### ISSUE THREAD

**Issue by PrathameshKesarkar** [nickbutcher/AdaptiveIconPlayground#10]
I have seen Google Calendar is Changing it's date everyday within the icon. Is this can be done using Adaptive Icon's or is there is something else to it. I am pretty sure they haven't bundled 31 icons as this would be resource consuming.

**PS: I ❤️ your plaid app though**

**Comment by nickbutcher** [comment]
Thanks!

No; it's not possible to dynamically change your icon. I'm not certain how Calendar does it but likely by working with the Launcher.
