### ISSUE TITLE
"There was a problem parsing the package"

### ISSUE THREAD

**Issue by itayganor** [nickbutcher/AdaptiveIconPlayground#7]
Hey,
I'm trying to install your APK on my Galaxy S8, but I get a popup that says there was a problem parsing the package. What can I do in order to solve this?

**Comment by NightlyNexus** [comment]
https://github.com/nickbutcher/AdaptiveIconPlayground/issues/3#issuecomment-315149240

**Comment by nickbutcher** [comment]
Yup, this requires API26 (when `AdaptiveIconDrawable` was introduced) so closing this as WAI.
