### ISSUE TITLE
Possible to avoid using Adaptive icons?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nickbutcher/AdaptiveIconPlayground#9]
I don't like them at all. Makes the icon itself smaller, and uses useless space for background, covering more space of the wallpaper. Not only that, but it gives the same feeling I had when looking on Chinese devices, which forced all icons to have same shape, no matter what's the result. Even with Google's own apps, I see it doesn't look well at all. YouTube app, for example, now has the shaped background (rectangle/circle/etc...) and a red rectangle in it, of the icon itself. It doesn't make sense...

Is it possible, as either a developer or a user, to avoid them ?
Is it possible to give the user the option to avoid them?

**Comment by nickbutcher** [comment]
To each their own.

> Is it possible, as either a developer or a user, to avoid them ?

Developers can… not provide an adaptive icon. It's up to them. Some launchers may still 'plate' them on the adaptive shape. As a user, you can install a launcher that doesn't use adaptive icons.

Closing as this is not an issue with this project.

**Comment by AndroidDeveloperLB** [comment]
Sorry for that, but it is related to the topic itself and I had nobody in Google to ask this, as it's really annoying for me to see icons this way. 
What do you mean "plate" them on the adaptive shape? What does it mean?
How would a launcher take an app with adaptive icon, and use the normal icon instead?

**Comment by nickbutcher** [comment]
[See here](https://medium.com/google-design/understanding-android-adaptive-icons-cee8a9de93e2#9f84) for what I mean by plating.

As adaptive icons are only used on Android Oreo, most apps will ship a 'standard' icon for the next few years for older devices. A launcher may choose to show that icon instead.

**Comment by AndroidDeveloperLB** [comment]
Sorry but I still don't get what "plate" means for you here. It isn't mentioned on the website you've shown. You mean that some launchers might add an extra background layer, in addition to the one of the adaptive icon (the mask)?

About choosing the standard icon, I'd like to know of a method that will always work, even if the minSdk is of Android O.

About the article, I have to agree with this:

> For icon makers, it’s easy to see this as losing some freedom.
And the image taken from Samsung device ([here](https://cdn-images-1.medium.com/max/880/1*txJIqPR63vrKoojTASTT5Q.jpeg)) only shows how bad such a thing can look like. This is very very similar to how I see the new adaptive icons. Just look what I got on Google's launcher on my Nexus 5x :
![screenshot_20170828-212944](https://user-images.githubusercontent.com/5357526/30166968-924ff306-93ed-11e7-8521-d9923789420c.png)
Even if all had the same shape (which I'm against), it would still look bad.

Really, if I don't have a fix of this issue as a user, I'd like to know if I can do something as a developer...
Just because now we can have special effects on the adaptive icons, doesn't make it look pretty to me, or worth this huge change.

**Comment by nickbutcher** [comment]
>Sorry but I still don't get what "plate" means for you here. It isn't mentioned on the website you've shown. You mean that some launchers might add an extra background layer, in addition to the one of the adaptive icon (the mask)?

Yes by 'plate' I mean placing the non-adaptive icon onto a background shape.

>I'd like to know if I can do something as a developer

As I said, you can just not provide an adaptive icon in your app. You can't control how launchers will use this icon (i.e. they might place them on a background) just like you can't control if users use icon packs right now.

**Comment by AndroidDeveloperLB** [comment]
So there could be 2 backgrounds?

About me as developer, I meant as a solution for me as a user. I can't of course change the code of all apps on the play store... 
I mean suppose I'm a launcher developer or developer that creates shortcuts to apps, and I want apps icons would appear without their mask background. Maybe I could fetch the inner icon of the adaptive one, stretch it a bit and use it as the new icon?

Maybe `(AdaptiveIconDrawable) drawable).getForeground()` , and then crop the 72x72 dp part of it that matters:
https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable.html

Or something similar?

**Comment by nickbutcher** [comment]
This sounds very brittle. Adaptive Icons are designed to work with two layers and just using one on it's own may have unexpected results. What if the central glyph is on the background and the foreground provides other effects?

I'm closing this conversation as it's way way off topic for this forum.
